#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM microsoft/aspnetcore:2.0-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0-nanoserver-1709 AS build
WORKDIR /src
COPY ["API-Management/API-Management.csproj", "API-Management/"]
RUN dotnet restore "API-Management/API-Management.csproj"
COPY . .
WORKDIR "/src/API-Management"
RUN dotnet build "API-Management.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "API-Management.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "API-Management.dll"]